# Generated by Django 4.2.3 on 2023-07-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgim',
            old_name='date',
            new_name='title',
        ),
    ]
